### ISSUE TITLE
Product Image Issue for template-product.liquid

### ISSUE THREAD

**Issue by pb-code** [kondasoft/ks-bootshop#92]
Hello,

The product images will only display on the product page if we add the images to variant options.

Products without variants will not show the product images.

**Comment by alvinkonda** [comment]
Fixed! Please replace this file on your Shopify store 

https://github.com/kondasoft/ks-bootshop/blob/master/snippets/product-gallery.liquid

If you are not sure how to do this please let me know

**Comment by pb-code** [comment]
working now - thank you Alvin!

**Comment by iusty64** [comment]
Hey, do I just replace 'product-gallery.liquid' in my shopify store with this one?(because they're the same and the issue still persists)
